// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

function _timeout (cb, t, res, tmp) {

    var rv = new tame.Rendezvous ();
    var arr = [];
    tmp[0] = rv.mkev (true, arr);
    setTimeout (rv.mkev (false), t);
    twait { rv.wait (mkevent (var which)); }
    if (res) { res[0] = which; }
    cb.apply (null, arr);
};

function timeout (cb, t, res) {
    var tmp = [];
    _timeout (cb, t, res, tmp);
    return tmp[0];
};

exports.timeout = timeout;
