// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

var res = 0;
var i = 0;

function foo (i, cb) {
    await { setTimeout (defer (), i); }
    cb (i);
};


var ok = true;

exports["a test of fulfill values"] = {

    run : function (cb) {
        
        for (var i = 0; i < 20; i++) {
            var x = 3 * Math.random ();
            await { foo (x, defer (var y, z)); }
            if (x != y) { ok = false; }
        }
        
        for (var i = 0; i < 20; i++) {
            var x = 3 * Math.random ();
            await { foo (x, defer (var res)); }
            if (x != res) { ok = false; }
        }
        
        cb ();

    },

    check : function () {
	    assert.ok (ok, "fulfilled with proper values");
    }

};
