// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var slots = {};
var assert = require ("assert");

var slots = {};
var n = 10;

exports["test nested serial/parallel"] = {
    
    run : function (cb) {

        await {
            for (var i = 0; i < n; i++) {
                (function (cb) {
                    var my_i = i;
                    await { setTimeout (defer (), 5*Math.random ()); }
                    await { setTimeout (defer (), 4*Math.random ()); }
                    slots[my_i] = true;
                    cb();
                })(defer ());
            }
        }
	    cb();
    },
    
    check : function () {
        for (var i = 0; i < n; i++) {
	        assert.ok(slots[i], "slots[" + i + "] is set!");
        }
    }
};
