// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var slots = {};
var n = 10;
var assert = require ("assert");

exports["test await with no curlies"] = {
    
    run : function (cb) {
        for (var i = 0; i < n; i++) {
            await setTimeout (defer (), 3 * Math.random ());
            slots[i] = 1;
        }
	    cb();
    },
    
    check : function () {
	    for (var i = 0; i < n; i++) {
	        assert.ok (slots[i], "slot[" + i + "] is set");
	    }
    }
};
