// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

var dec = 0.2;

exports["test of 'this' inside of a tamed class"] = {

    run  : function (cb) {
        cb ();
    },

    check : function () {
      // This is a compilation test to make sure that decimal numbers work.
      // No runtime test is required.
    }

};

