// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

var dec = 0.2, b = -.11, c = -1.222, d = 10000.111111, e = -1000;

exports["test that decimal literals compile"] = {

    run  : function (cb) {
        cb ();
    },

    check : function () {
      // This is a compilation test to make sure that decimal numbers work.
      // No runtime test is required.
    }

};

