// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

function eeStyle (cb) {
    var ret = {};
    setTimeout (function () { ret.slot = 10; cb (); }, 4);
    return ret;
};

var tmp;

exports["test that EventEmitter-type-things works"] = {

    run  : function (cb) {
        await { 
            tmp = eeStyle (defer ());
        }
        cb ();
    },

    check : function () {
        assert.equal (tmp.slot, 10);
    }

};

