// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

var side_effect = 0;

function do_side_effect () {
    side_effect = 1;
    return 10;
};

function foo () {
    await setTimeout (defer (), 2);
    return do_side_effect ();
};

var tmp;

exports["test that return value side effects happen"] = {
    
    run  : function (cb) {
        foo ();
        await setTimeout (defer (), 5);
        cb ();
    },

    check : function () {
        assert.equal (side_effect, 1);
    }

};

