// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var n = 30;
var skip = 20;
var slots = {};
var assert = require ("assert");

exports["break and continue"] = {

    run : function (cb) {
	    var i = 0;
	    while (1) {
	        slots[i] = 0;
	        await { setTimeout (defer (), 1); }
            
	        if (i == skip) {
		        i++;
		        continue;
	        }
	        slots[i] = 1;
	        i++;
	        if (i == n) {
		        break;
	        }
	    }
	    cb ();
    },
    
    check : function () {
	    var i = 0;
	    for (i = 0; i < n; i++) {
	        if (i != skip) {
		        assert.ok (slots[i], "iter " + i + 
			               ": all slots but skip=" + skip);
	        } else {
		        assert.ok (!slots[i], "iter " + i + 
			               ":  all slots but skip=" + skip);
	        }
	    }
	    assert.ok (!slots[i], "stop at slot=" + n);
    }

};
