// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");
var ok = false;

function foo (autocb) 
{
    await setTimeout (defer(), 1);
    return true;
}

exports["simple autocb operations"] = {
    
    run : function (autocb) {
	await foo (defer (var b));
	ok = b;
    },
    
    check : function () {
	assert.ok (ok, "ok was set via autocb");
    }
};
