// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

var sum = 0;
var i = 0;

exports["parsing and lexing of equalities"] = {

    run : function (cb) {
        if (1 === 1) { i++; }
        if (1 == 1) { i++; }
        if (1 != 2) { i++; }
        if (1 !== 2) { i++; }
        if (3 <= 4) { i++; }
        if (!!30) { i++; }
        if (5 >= 1) { i++; }
	cb();
    },

    check : function () {
	assert.equal (i, 7, "all 7 worked");
    }

};
