// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

var listA = [];
var listB = [];


exports["for..in iteration"] = {

    run : function (cb) {
        
	    var i = 0;
	    for (i = 0; i < 10; i++) {
	        await { setTimeout (defer (), 10* Math.random ()); }
	        listA.push (i);
	    }
	    for ( ; i < 20; i++) {
	        listA.push (i);
	    }
	    while (true) {
	        if (i >= 30) {
		        break;
	        }
	        await { setTimeout (defer (), 10* Math.random ()); }
	        listA.push (i);
	        i++;
	    }
	    while (true) {
	        if (i >= 40) {
		        break;
	        }
	        listA.push (i);
	        i++;
	    }
	    cb ();
    },
    
    check : function () {
	    for (var i = 0; i < 40; i++) { listB.push (i); }
	    assert.deepEqual (listA, listB, "list equivalence");
    }
    
};
