// -*- mode: javascript; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-

"use strict";

var assert = require ("assert");

var res = 0;

function foo (cb) {
    await { setTimeout (defer (), 10 * Math.random ()); }
    res++;
    cb();
};

exports["parser variations"] = {
    
    run : function (cb) {
	    if (true) await foo (defer ());
	    res++;
	    cb();
    },
    check : function () {
	    assert.equal (res, 2, "both increments fired");
    }

};
